apiVersion: apps/v1
kind: Deployment
metadata:
  name: dowkproj-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dowkproj
  template:
    metadata:
      labels:
        app: dowkproj
    spec:
      volumes:
      - name: dowkproj-image
        persistentVolumeClaim:
          claimName: dowkproject-claim
      containers:
        -  name: dowkproj
           image: jkur00/dowkproj:0.7
           volumeMounts:
             - mountPath: /usr/src/kwbProjApp/files # Default for the app, make sure it matches
               name: dowkproj-image

