apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpongapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpongapp
  template:
    metadata:
      labels:
        app: pingpongapp
    spec:
      volumes:
          - name: shared-logoutput
            persistentVolumeClaim:
              claimName: logoutput-claim
      containers:
      - name: pingpongapp
        image: jkur00/pingpongapp:0.1.5
        volumeMounts:
          - mountPath: /usr/src/app/logs
            name: shared-logoutput