apiVersion: v1
kind: Service
metadata:
  name: pingpongapp-svc
spec:
  type: ClusterIP
  selector:
    app: pingpongapp
  ports:
  - port: 3003
    protocol: TCP
    targetPort: 3000  # Change to whatever is delcared by process.env.PORT if needed
