apiVersion: v1
kind: Service
metadata:
  name: pingpongapp-svc
spec:
  type: ClusterIP
  selector:
    app: pingpongapp
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3006  # Change to whatever is delcared by process.env.PORT if needed
